spring:
  datasource:
   url: jdbc:mysql://localhost:3306/sky_take_out
   username: root
   password: xnsdmn
   driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
   host: 127.0.0.1
   port: 6379
   database: 9
   password: 123456

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB


