server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/sky_take_out
    username: root
    password: xnsdmn
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ${sky.redis.host}
    port: ${sky.redis.port}
    database: ${sky.redis.database}
    password: ${sky.redis.password}
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  wechat:
    appid: wxe7ca53b8c3a30de3
    secret: a6d803d3f1d6f4462073ad377fbd31e1
